name: Go package

on:
  push:
    branches:
      - "**"

env:
  GOPRIVATE: "github.com/fabienjuif"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GOLANG_PRIVATE_REPO }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Lint
        run: |
          go install mvdan.cc/gofumpt@latest
          make test-format

      - name: Go Mod Tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
